apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubecluster
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kubecluster
    spec:
      containers:
        - name: kubecluster
          image: riky126/cicd-demo:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
 name: helloworld
spec:
 type: NodePort
 selector:
   app: helloworld
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: helloworld