{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "demo-chart.serviceAccountName" . }}
  labels:
{{ include "demo-chart.labels" . | indent 4 }}
{{- end -}}
